### ISSUE TITLE
gereksiz init state

### ISSUE THREAD

**Issue by VB10** [dilberkilic/Mobx_RESTful_API_Flutter#11]
https://github.com/dilberkilic/Mobx_RESTful_API_Flutter/blob/d32d35ee6a1d2770660e2c3d79e505d32a74cd84/lib/Pages/home_page.dart#L13

kullanmityorsak silelim yine degeleri constant

**Comment by dilberkilic** [comment]
Gereksiz bir initState() koymuşum.
