### ISSUE TITLE
Switch states

### ISSUE THREAD

**Issue by VB10** [dilberkilic/Mobx_RESTful_API_Flutter#6]
https://github.com/dilberkilic/Mobx_RESTful_API_Flutter/blob/d32d35ee6a1d2770660e2c3d79e505d32a74cd84/lib/Pages/users_list.dart#L58

her state icin extract widget diyip orayi daha temiz tutabilrisin
_ListUserLoaded gibi

**Comment by dilberkilic** [comment]
Teşekkür ederim. Temiz kod yazmaya daha çok dikkat etmeliyim.
